In [48]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
import time
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd


options = Options()
options.add_argument("start-maximized")
# Avoiding detection
options.add_argument('--disable-blink-features=AutomationControlled')

#s = Service('chromedriver.exe')
driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)

C:\Users\Muhammad Ansar\AppData\Local\Temp\ipykernel_15184\4248854214.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)

In [49]:
import csv
from csv import reader
file = []
filename = 'Date.csv'
with open(filename, 'r') as f:
    reader = csv.reader(f)
    for row in reader:
       file.extend(row)

In [50]:
URL="https://www.iberostar.com/en/"
driver.get(URL)
time.sleep(10)

In [51]:
#driver.implicitly_wait(20)
driver.find_element("xpath", '//*[@id="agree-cookies"]').click()
time.sleep(5)

In [52]:
final=[]

In [53]:
for a,b in zip(file[2::2],file[3::2]):
    
    driver.get(f"https://booking.iberostar.com/Reservations/availabilityNoDispo?codiconc=315&conccodi=76&cp_tealium=&edadpersona0_0=30&edadpersona0_1=30&fechafin={b}&fechaini={a}&idiocodi=2&idiomercodi=en&monecodi=EUR&numerohabitaciones=1&numeropersonas0=2&ok_promo=0&origen_soporte=IBE&search_origin=hotel")
    time.sleep(10)
    try:
        k=driver.find_element("xpath", '//*[@id="cphMain_pnlRoom"]/div/div/div[2]/div[1]/div/div[3]/div[2]').text
        #print(k)
        final.append(k)
        final.append(b)
    except:
        a="N/A"
        #print(a)
        final.append(a)
        final.append(b)
        pass
    time.sleep(2)

In [54]:
lb,lt ,lp= [],[],[]
for i,j in zip(final[0::2],final[1::2]):
    #print(i[0])
    lb.append(i)
    lt.append(j)
    lp.append("7 Nights")

dictionary = {
    "nights": lp,
    "dates": lt,
    "price": lb
}

import pandas as pd
pd = pd.DataFrame(dictionary)
pd['price'] = pd['price'].str[17:26]
df= pd.T # or df1.transpose()

In [55]:
final1=[]

In [56]:
for a,b in zip(file[2::2],file[3::2]):
    
    driver.get(f"https://booking.iberostar.com/Reservations/availabilityNoDispo?codiconc=315&conccodi=76&cp_tealium=&edadpersona0_0=5&edadpersona0_1=30&edadpersona0_2=30&fechafin={b}&fechaini={a}&idiocodi=2&idiomercodi=en&monecodi=EUR&numerohabitaciones=1&numeropersonas0=3&ok_promo=0&origen_soporte=IBE&search_origin=hotel")
    time.sleep(10)
    try:
        k=driver.find_element("xpath", '//*[@id="cphMain_pnlRoom"]/div/div/div[2]/div[1]/div/div[3]/div[2]').text
        #print(k)
        final1.append(k)
        final1.append(b)
    except:
        a="N/A"
        #print(a)
        final1.append(a)
        final1.append(b)
        pass
    time.sleep(2)

In [57]:
lb,lt ,lp= [],[],[]
for i,j in zip(final1[0::2],final1[1::2]):
    #print(i[0])
    lb.append(i)
    lt.append(j)
    lp.append("7 Nights")

dictionary = {
    "nights": lp,
    "dates": lt,
    "price": lb
}

import pandas as pd
pd = pd.DataFrame(dictionary)
pd['price'] = pd['price'].str[17:26]

df1= pd.T # or df1.transpose()

In [58]:
final2=[]

In [59]:
for a,b in zip(file[2::2],file[3::2]):
    
    driver.get(f"https://booking.iberostar.com/Reservations/availabilityNoDispo?codiconc=315&conccodi=76&cp_tealium=&edadpersona0_0=5&edadpersona0_1=11&edadpersona0_2=30&edadpersona0_3=30&fechafin={b}&fechaini={a}&idiocodi=2&idiomercodi=en&monecodi=EUR&numerohabitaciones=1&numeropersonas0=4&ok_promo=0&origen_soporte=IBE&search_origin=hotel")
    time.sleep(10)
    try:
        k=driver.find_element("xpath", '//*[@id="cphMain_pnlRoom"]/div/div/div[2]/div[1]/div/div[3]/div[2]').text
        #print(k)
        final2.append(k)
        final2.append(b)
    except:
        a="N/A"
        #print(a)
        final2.append(a)
        final2.append(b)
        pass
    time.sleep(2)

In [60]:
lb,lt ,lp= [],[],[]
for i,j in zip(final2[0::2],final2[1::2]):
    #print(i[0])
    lb.append(i)
    lt.append(j)
    lp.append("7 Nights")

dictionary = {
    "nights": lp,
    "dates": lt,
    "price": lb
}

import pandas as pd
pd = pd.DataFrame(dictionary)
pd['price'] = pd['price'].str[17:26]
df2= pd.T # or df1.transpose()

In [61]:
import pandas as pd


frames = [df,df1,df2]

result = pd.concat(frames)
display(result)

,0,1,2,3,4,5,6,7,8,9,10,11
nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,,,,,,,,4196 EUR,,,4196 EUR
nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,,,,,,5770 EUR,,,5770 EUR,,
nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,,,,,,,,7344 EUR,,,

In [62]:
import numpy as np
result = result.replace(r'^\s*$',str(np.nan) , regex=True)
#print(result)

In [63]:
result.insert(0,'URL','')

In [64]:
dff=result

In [65]:
dff.iat[2, 0] = URL
dff.iat[5, 0] = URL
dff.iat[8, 0] = URL

In [66]:
result.insert(0,'Info','')

In [67]:
dff=result

In [68]:
dff.iat[0, 0] = "7 days 2 pax All-Inclusive"
dff.iat[3, 0] = "7 days 2 + 1(5years) pax All-Inclusive"
dff.iat[6, 0] = "7 days 2 + 2 (5,11 years) pax All-Inclusive"
dff.iat[1, 0]=  "Iberostar Club Cala Barca"
dff.iat[4, 0]=  "Iberostar Club Cala Barca"
dff.iat[7, 0]=  "Iberostar Club Cala Barca"

In [69]:
dff

,Info,URL,0,1,2,3,4,5,6,7,8,9,10,11
nights,7 days 2 pax All-Inclusive,,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,Iberostar Club Cala Barca,,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,https://www.iberostar.com/en/,nan,nan,nan,nan,nan,nan,nan,nan,4196 EUR,nan,nan,4196 EUR
nights,7 days 2 + 1(5years) pax All-Inclusive,,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,Iberostar Club Cala Barca,,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,https://www.iberostar.com/en/,nan,nan,nan,nan,nan,nan,5770 EUR,nan,nan,5770 EUR,nan,nan
nights,"7 days 2 + 2 (5,11 years) pax All-Inclusive",,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights,7 Nights
dates,Iberostar Club Cala Barca,,end_date,18/03/2023,19/03/2023,20/03/2023,21/03/2023,22/03/2023,23/03/2023,24/03/2023,25/03/2023,26/03/2023,27/03/2023,28/03/2023
price,,https://www.iberostar.com/en/,nan,nan,nan,nan,nan,nan,nan,nan,7344 EUR,nan,nan,nan

In [70]:
dff.to_csv("scrap.csv")
driver.quit()